pipeline {
    agent any
    stages {
        stage('One') {
            steps {
                echo 'This is stage one'   
            }
        }
        stage('Two') {
            steps {
                echo 'This is stage two'
            }
        }
        stage('Three') {
            steps {
                echo 'This is stage three'
            }
        }
    }
}
